# Generated by Django 5.2.17 on 2026-09-23 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itEquipmentWarehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_standalone',
            field=models.BooleanField(default=False, verbose_name='Самостоятельное устройство'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField(verbose_name='Название модели')),
                ('serial_number', models.TextField(verbose_name='Серийный номер')),
                ('specifications', models.TextField(verbose_name='Технические характеристики')),
                ('quantity_stock', models.IntegerField(verbose_name='Кол-во на складе')),
                ('status', models.TextField(verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itEquipmentWarehouse.category')),
            ],
        ),
    ]
