# Generated by Django 5.2.17 on 2026-09-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itEquipmentWarehouse', '0002_alter_category_options_alter_category_is_standalone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='components',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AlterField(
            model_name='components',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itEquipmentWarehouse.category'),
        ),
    ]
