# Generated by Django 5.2.17 on 2026-09-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itEquipmentWarehouse', '0003_alter_components_options_alter_components_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='components',
            new_name='Component',
        ),
    ]
