# Generated by Django 5.2 on 2026-09-30 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itEquipmentWarehouse', '0004_rename_components_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.TextField(default='В наличии', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='BuildRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='assembly', verbose_name='Тип заявки')),
                ('target_workload', models.CharField(verbose_name='Назначение ПК')),
                ('status', models.CharField(default='В ожидании', verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_builds', to=settings.AUTH_USER_MODEL, verbose_name='Сборщик')),
            ],
            options={
                'verbose_name': 'Заявка на сборку',
                'verbose_name_plural': 'Заявки на сборку',
            },
        ),
        migrations.CreateModel(
            name='AssemblyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время установки')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='itEquipmentWarehouse.component', verbose_name='Деталь')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itEquipmentWarehouse.buildrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Деталь сборки',
                'verbose_name_plural': 'Детали сборок',
            },
        ),
        migrations.CreateModel(
            name='HandoverAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_tag', models.CharField(unique=True, verbose_name='Инвентарный номер')),
                ('workplace_location', models.CharField(verbose_name='Кабинет/Рабочее место')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписания')),
                ('issuer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts_issued', to=settings.AUTH_USER_MODEL, verbose_name='Выдал инженер')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='itEquipmentWarehouse.buildrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Акт выдачи',
                'verbose_name_plural': 'Акты выдачи',
            },
        ),
    ]
